name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker network create vertx-4-reactive-rest-api-network
      - run: docker-compose up &
      - run: mvn package -DskipTests
      - run: java -jar target/vertx-4-reactive-rest-api-0.1-SNAPSHOT-fat.jar > log 2>&1 &
      - run: curl -sS http://localhost:8888/api/v1/books
      - run: sleep 10
      - run: curl -sS http://localhost:8888/api/v1/bookz
      - run: cat log
